language: node_js

node_js:
  - "o"

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - openssl aes-256-cbc -K $encrypted_0d682b85e21c_key -iv $encrypted_0d682b85e21c_iv -in deploy_rsa.enc -out deploy_rsa -d

install:
  - npm install

script:
  - npm run config -- --env=prod
  - npm run build
