language: node_js

# Disable sudo to enable ssh_known_hosts
sudo: false

addons:
  ssh_known_hosts: "blog.florimondmanca.com"

node_js:
  - "node"

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm install

script:
  - npm run config -- --env=prod
  - npm run build

before_deploy:
  - source scripts/before_deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master

env:
  global:
    - ADMIN_SITE_URL: https://api.florimondmanca.com/admin
    - API_URL: https://api.florimondmanca.com/api
    - RSS_FEED_URL: feed://api.florimondmanca.com/blog/feed
    - BACKEND_URL: https://api.florimondmanca.com
