language: node_js

ssh_known_hosts:
  - "www.florimondmanca.com"

node_js:
  - "node"

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - openssl aes-256-cbc -K $encrypted_0d682b85e21c_key -iv $encrypted_0d682b85e21c_iv -in deploy_rsa.enc -out deploy_rsa -d

install:
  - npm install

script:
  - npm run config -- --env=prod
  - npm run build

before_deploy:
  - bash scripts/before_deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master

env:
  global:
    - ADMIN_SITE_URL: https://api.florimondmanca.com/admin
    - API_URL: https://api.florimondmanca.com
  secure: "B7FTqp+73Vwb+2U4UhMfpaKI4SoHoYLfCZgG2B4YNw5u6+docoIcav1jwtf6f9eJmBC8sF+FYSrsFRRLQwtnWMIVjns66KAY5hysItbf10uauDUupMK7NcITMK45cprhzm26lSdX6RciXDuoTkcj5EGufypIxa6k2jRTM0HZNIRaGgYOxgITBtU3CfNUShqZtGCRABvdidQRP2ux7khc6gHzj8UAPoo73WHzBdCnLa2wjIxywb0sZkR8ORwMrDVtzGUiTFXXem8m0MW+EVakxDZAoZM3qu6vuLok93qzdDSfvFADsRR2MrhgtO1quCyf0xZxlxrFMO6HByA+OluacW+8u/tBwN8KUtB53KfklP3GsfkABQJBN37EZmmJ9IebD65hEscda0XrlsUGreTQwz/odZM5nWLUUG9F/dcxPZY0kqwz14ZlHFcmyk5Ol1JlZi7MODkCu7seyEUxDgOgBptC0F3pkhTVqpuY4xG2d1pA6CcPBW+4u9YFJ0RDs+l1Do+u6Yohh342NyNWaX1mPAjEzguWB2rUtGO077YmCrf2yTD2WXLEz2IvjkENwLAfe3kUx7LEDJywpy0F6m0JIHZeezYksNn/rCs0Xu5/r8Jzbni9d5Wu6HHmakgYrLsKNWLkiiQr+jvkISbeeJlXHqKPgUpgi2BrS6J2Or2i1O0="
