language: node_js

ssh_known_hosts:
  - "www.florimondmanca.com"

node_js:
  - "node"

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - openssl aes-256-cbc -K $encrypted_0d682b85e21c_key -iv $encrypted_0d682b85e21c_iv -in deploy_rsa.enc -out deploy_rsa -d

install:
  - npm install

script:
  - npm run config -- --env=prod
  - npm run build

before_deploy:
  # Setup SSH to server
  - openssl aes-256-cbc -K $encrypted_0d682b85e21c_key -iv $encrypted_0d682b85e21c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  # Install CaptainDuckDuck CLI
  - npm install -g captainduckduck

deploy:
  provider: script
  skip_cleanup: true
  script:
    # Copy dist folder to Captain's Nginx shared folder
    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@www.florimondmanca.com:/captain/nginx-shared
    # Deploy use CaptainDuckDuck
    - captainduckduck deploy -s -h https://captain.florimondmanca.com -a www -p $CAPTAIN_PASSWORD
  on:
    branch: master

env:
  secure: "GfXrOBL2WPGv7TNH7nVM9qZc1uD1yd/tTgixNopfdqMmSmjZCG7QpeaHAeEHzo7t2jxmUzwn940Pgraw9T4Z2pK1W32O4OAA8HoRQimlqbVa8coZ1trPn+EJhlFyjBHqy7BHzoeUOYiBV/wrj+1NFrn49J50dW1SMwghAjbXKwUR7YnDlMIcUFTuAHrxi69gCzvsTrXtfamPMSPqUF7vLTYnIsn33jbQI35kZVZLcvxBk3Tv8KAmcR+2GxW9OdqDESEw4aC78B/Vu+lxc5EIB6IvOLvFd3DlUWjoniT3yxveMl6D9IfKaV7g4e12Cnfr59iIsujg9h4T8U1lv92d4hIg6zOoffsVGYZ8/Uk+wOe2bkNZrXzl50mwn591jNcD0Ood/ykO3wgM5puBbikG+yBj0xp96ae+5VpHS7KbN3Y5FLkGfRbzHZWaYE5wEreHx3wiiI1YASxFH/1C5U9zeiDqg+Ja8k8p3iqQeYOSOE1pxgzITgYlafkYR8s8Vc8itZk0rrmiLJOxq7vOFlWYAutMhBysbD55LbK8tAhl+nHBVroVPhOkujfVRuHhj5uMPr0yh2GUpDx4oPcwQB9tWbmBDL6Yu3v+3O3gftqjE1MUDJ/gUcCrvxL9+oOtzNObtEd4egkirkYMHHJIGzvNqrIP2AwyOzuZaqL0J7L9oR0="
