language: node_js

# Disable sudo to enable ssh_known_hosts
sudo: false

addons:
  ssh_known_hosts: "www.florimondmanca.com"

node_js:
  - "node"

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm install

script:
  - npm run config -- --env=prod
  - npm run build

before_deploy:
  - echo "Setting up deploy SSH keys…"
  - openssl aes-256-cbc -K $encrypted_0d682b85e21c_key -iv $encrypted_0d682b85e21c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo "Installing CaptainDuckDuck CLI…"
  - npm install -g captainduckduck

deploy:
  provider: script
  skip_cleanup: true
  # Copy dist folder on remote's Nginx shared folder,
  # and trigger Captain deploument
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@www.florimondmanca.com:/captain/nginx-shared; captainduckduck deploy -s -h https://captain.florimondmanca.com -a www -p $CAPTAIN_PASSWORD

  on:
    branch: master

env:
  global:
    - ADMIN_SITE_URL: https://api.florimondmanca.com/admin
    - API_URL: https://api.florimondmanca.com
