language: node_js

# Disable sudo to enable ssh_known_hosts
sudo: false

addons:
  ssh_known_hosts: "captain.florimondmanca.com"

node_js:
  - "node"

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - openssl aes-256-cbc -K $encrypted_e1e2a71240b7_key -iv $encrypted_e1e2a71240b7_iv -in deploy_rsa.enc -out .travis/deploy_rsa -d

install:
  - npm install -g caprover
  - npm install

script:
  - npm run config -- --env=prod
  - npm run build
  - npm run setup:http2
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master

env:
  global:
    - BACKEND_URL: "https://api.florimond.dev"
